eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

rabbitmq:
  exchanges:
    default:
      type: topic
  bindings:
    microservice1:
      routingKey: order-routing-key